name: Cek Kode HTML

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: action/checkout@v47

    - name: Install HTMLint
      run: npm install -g HTMLint

    - name: Periksa HTML
      run: htmlint "**/*.html"